defaults: &defaults
  working_directory: ~/workspace/repo
  docker:
    - image: circleci/node:9.11.2

to_persist: &to_persist
  root: ~/workspace
  paths:
    - repo/*

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          <<: *to_persist

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Lint JavaScript code
          command: npm run lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Running unit and integration tests
          command: |
            npm run test:unit
      - persist_to_workspace:
          <<: *to_persist

workflows:
  version: 2
  default:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - checkout